services:
  chart-ocr:
    build: .
    container_name: chart-ocr
    restart: always
    ports:
      - "5050:5050"
    environment:
      - MINIO_ENDPOINT=https://upload.hamalv.ir
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=1MP6rLEyoGKVAoUaNJoMDW2F
      - MINIO_BUCKET=chart-ocr-datasets
    volumes:
      - ./uploads:/app/uploads
      - ./extracted_output:/app/extracted_output
    networks:
      - web

networks:
  web:
    external: true
